exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('courses').del()
    .then(function () {
      // Inserts seed entries
      return knex('courses').insert([
        {id: 1, name: 'Titirangi Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://www.titirangigolf.co.nz/wp-content/uploads/titirangi-golf-slider_01.jpg', website: ''},
        {id: 2, name: 'Waipu Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: 'https://www.google.com/search?q=waipu%20golf%20course&tbm=isch&safe=off&tbs=isz:l&rlz=1C1CHBF_enNZ892NZ892&hl=en&sa=X&ved=0CAIQpwVqFwoTCLDy4r_79_ACFQAAAAAdAAAAABAC&biw=1349&bih=600#imgrc=VLSdkiARBszu-M', website: ''},
        {id: 3, name: 'Golf Warehouse & Driving Range Ellerslie', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/8accaa8/2147483647/strip/true/crop/811x523+33+0/resize/930x600!/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2Fc8%2Fed%2F4bb0876c94de945e5dd102571d5a%2F70576.jpg', website: ''},
        {id: 4, name: 'Lakes Resort Pauanui', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: 'https://www.lakesresort.com/images/darren1.JPG', website: ''},
        {id: 5, name: 'Terrace Downs', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: 'https://www.google.com/search?q=terrace%20downs%20golf&tbm=isch&safe=off&tbs=isz:l&rlz=1C1CHBF_enNZ892NZ892&hl=en&sa=X&ved=0CAIQpwVqFwoTCPCRlur79_ACFQAAAAAdAAAAABAC&biw=1349&bih=600#imgrc=leG4isoTtNNSqM', website: ''},
        {id: 6, name: 'Mangawhai Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/817a105/2147483647/strip/true/crop/750x484+0+9/resize/930x600!/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2F57%2F19%2Fa40c471f7dfa9144c8142bc1a5bf%2F19399.jpg', website: ''},
        {id: 7, name: 'Nelson Golf Club', country: 'New Zealand', region: 'Nelson City', regionNumber: 8, photo: 'https://www.nelsongolf.co.nz/wp-content/uploads/2015/05/Nelson-GC-Am250414_180-1-3-Background1600x1000.jpg', website: ''},
        {id: 8, name: 'New Plymouth Golf Club (Ngāmotu Links)', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: 'https://assets.hole19golf.com/course_images/images/000/070/956/standard/d5c5efca8cdadb201db2c8b5e1ce1b665da9b24a.jpeg?1582812907', website: ''},
        {id: 9, name: 'Tauranga Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: 'http://s3.ap-southeast-2.amazonaws.com/nz.clubassets/400/email/images/IMG_1021-600.jpg', website: ''},
        {id: 10, name: 'Patutahi Golf Club', country: 'New Zealand', region: 'Gisborne District', regionNumber: 2, photo: 'https://cdn.allsquaregolf.com/pictures/pictures/000/030/937/large/poverty_bay_golf_club_cover_picture.jpg', website: ''},
        {id: 11, name: 'Cape Kidnappers Golf Course', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: 'https://golf.com/wp-content/uploads/2019/11/cape-kidnappers.jpg', website: ''},
        {id: 12, name: 'Manawatu Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/716a377/2147483647/strip/true/crop/1223x789+109+0/resize/930x600!/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2F0f%2F67%2F137f81b84322348f97f8eea2ae96%2F90132.jpg', website: ''},
        {id: 13, name: 'Blenheim Golf Club', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: 'http://sportsgroundproduction.blob.core.windows.net/cms/3195/39045/140567/47bf8911-693d-442f-9a1a-8eb3c819c18d_wo.jpg', website: ''},
        {id: 14, name: 'Totaradale Golf Club', country: 'New Zealand', region: 'Tasman District', regionNumber: 9, photo: 'https://www.totaradalegolf.co.nz/images/503091/app11.jpg', website: ''},
        {id: 15, name: 'Greymouth Golf Club', country: 'New Zealand', region: 'West Coast', regionNumber: 12, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/1388f2d/2147483647/strip/true/crop/1440x350+0+0/resize/1440x350!/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2F55%2Fe7%2F7c7b478d4bdbba7e8764361e0483%2F1440x350.jpg', website: ''},
        {id: 16, name: 'Wainuiomata', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: '', website: ''},
        {id: 17, name: 'Invercargill Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: 'https://invercargillgolf.co.nz/backend/wp-content/gallery/golf-course-images/sam_0108.jpg', website: ''},
        {id: 18, name: 'Chamberlain Park Public Golf Course', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://lh3.googleusercontent.com/proxy/9mr3mooHwAIPLMKJI4llCw3KEfM70tQi3L3cTwtzujU6w1mzl_8qNXDqv0OACOzBmKRF6z9aLZyytJUPfOfRdqNetouvKX_2i6b-3f11odUCCSRfRuYwJLQC9bjGHSioiVQ5Epv4kWM', website: ''},
        {id: 19, name: 'Hororata Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: 'https://lh3.googleusercontent.com/proxy/2zlSr3G4yLxwf0ijiKgqv3JCPd0XR1sqUhljj_f4IUqY-zZEWm49Ohnggy8IptFxsdeafn188A8W912fEA9Q3aRG213F0dhikeHzObCFLoQZsOOaA5nxKOTq0jn4BI_jQyTZI1m92GhHbV_KsncP3UYHSVFJSQ', website: ''},
        {id: 20, name: 'Waahi Taakaro Golf Course', country: 'New Zealand', region: 'Nelson City', regionNumber: 8, photo: 'https://www.golflinks.co.nz/images/Golf_Course_Images/Tasman/Waahi.jpeg', website: ''},
        {id: 21, name: 'Waihi Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: 'https://images.sunlive.co.nz/images/sunlive/Waihi-Golf-Club-002.jpg', website: ''},
        {id: 22, name: 'Mercury Bay Golf & Country Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: 'https://mercurybaygolf.co.nz/wp-content/uploads/hole2tee-Copy.jpg', website: ''}, 
        {id: 23, name: 'Fitzroy Golf Club Inc', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/1388f2d/2147483647/strip/true/crop/1440x350+0+0/resize/1440x350!/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2F55%2Fe7%2F7c7b478d4bdbba7e8764361e0483%2F1440x350.jpg', website: ''},
        {id: 24, name: 'Wanganui Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: 'https://assets.hole19golf.com/course_images/images/000/082/440/standard/d14b1edf9fe5fc0ad1b5f7a1d6c15a09e97ad9b4.jpeg?1615486446', website: ''},
        {id: 25, name: 'Royal Wellington Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: 'https://s3.ap-southeast-2.amazonaws.com/newzealand.travlr.com/uploads/images/venue/e19c55bdd3a0962f1d8c2ef5baac82b0.jpg', website: ''},
        {id: 26, name: 'Miramar Links Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/7230a29/2147483647/strip/true/crop/1440x929+0+15/resize/930x600!/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2Fa8%2Fe5%2F0f4c0536b690dd255efe7d06c0f7%2F97982.jpg', website: ''},
        {id: 27, name: 'Marlborough Golf Club', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: 'https://www.marlboroughgolfclub.co.uk/images/thumbs/slideshow/marlborough/1500x700/0-0-0-0/1/40_310.jpg', website: ''},
        {id: 28, name: 'Hokitika Golf Club', country: 'New Zealand', region: 'West Coast', regionNumber: 12, photo: 'https://lh3.googleusercontent.com/UzT_KhJmwyW3w5ymXSzxnxpfgZIOqxkKm08qgz9r15pHcrko_qOG3utPY9rgu8cOT_Fw9YbJ=w1080-h608-p-no-v0', website: ''},
        {id: 29, name: 'Balmacewen Golf Course', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: 'https://resources.stuff.co.nz/content/dam/images/1/8/2/g/8/e/image.related.StuffLandscapeSixteenByNine.710x400.182g18.png/1449265410387.jpg', website: ''},
        {id: 30, name: 'Chisholm Links', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: 'https://media-cdn.tripadvisor.com/media/photo-s/05/c4/83/19/chisholm-park-golf-club.jpg', website: ''},
        {id: 31, name: 'Wanaka Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: 'https://wanakagolf.co.nz/wp-content/uploads/2013/11/140501_WGC-Autumn_WEB_043-e1400499721539-1024x463.jpg', website: ''},
        {id: 32, name: 'Queenstown Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: 'https://www.newzealand.com/assets/Operator-Database/a37531efaf/img-1574390745-669-5724-p-7C2F9068-E785-9D45-58F103B026D30962-2544003__aWxvdmVrZWxseQo_FocalPointCropWzQyMCw5NjAsNTAsNTAsNzUsImpwZyIsNjUsMi41XQ.jpg', website: ''},
        {id: 33, name: 'Christchurch Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/26a18b5/2147483647/strip/true/crop/1440x929+0+15/resize/930x600!/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2F2e%2F14%2Fe7aa2994eaa6d2fbc4426047eefc%2F90010.jpg', website: ''},
        {id: 34, name: 'St. Andrews of Hamilton Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: 'https://www.newzealand.com/assets/Operator-Database/0a49c30a88/img-1577100010-2998-1284-p-E7A3216E-95AE-83E2-4EE725BF6B9CAC2D-2544003__aWxvdmVrZWxseQo_CropResizeWzYwMCwzMzgsNTAsImpwZyJd.jpg', website: ''},
        {id: 35, name: 'Howick Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://www.golflinks.co.nz/images/Golf_Course_Images/Auckland/Howick1.jpg'},
        {id: 36, name: 'Pakuranga Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://i2.wp.com/asliceofnzgolf.com/wp-content/uploads/2019/12/PAPA-scaled.jpg?resize=1038%2C576&ssl=1'},
        {id: 37, name: 'Muriwai Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://www.helloauckland.co.nz/img/slider/1448395169Web_Slider_1.jpg'},
        {id: 38, name: 'Waitakere Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://newzealandgolfdigest.co.nz/wp-content/uploads/2018/04/Auckland%E2%80%99s_Golf_Trail_FI.jpg'},
        {id: 39, name: 'North Shore Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://sportsgroundproduction.blob.core.windows.net/cms/libraryassets/Wallpaper/My%20Wallpapers/ed28d3b2-f628-46bf-b63a-a4a38fd43603.png', website: ''},
        {id: 40, name: 'Remuera Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://www.aucklandnz.com/sites/build_auckland/files/styles/carousel_banner/public/tourismnz/p-400289F5-AF53-A0D9-AFF9B5BB58DCB07E-2544003.jpg', website: ''},
        {id: 41, name: 'Redwood Park Golf Club Inc', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://www.aucklandnz.com/sites/build_auckland/files/styles/carousel_banner/public/tourismnz/p-368BA48A-CDB8-CC88-80CA7423CFDB9EFE-2544003.jpg', website: ''},
        {id: 42, name: 'Takapuna Golf Course', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/466f943/2147483647/strip/true/crop/800x450+0+25/resize/590x332!/format/jpg/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2Ffc%2F38%2Fa5d84c0072c738735f6a0086e3fd%2F19284.jpg', website: ''},
        {id: 43, name: 'RNZAF Auckland Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://sportsgroundproduction.blob.core.windows.net/cms/libraryassets/Wallpaper/My%20Wallpapers/ed28d3b2-f628-46bf-b63a-a4a38fd43603.png', website: ''},
        {id: 44, name: 'Wattle Downs Golf Course', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: 'https://golf-pass.brightspotcdn.com/dims4/default/4084154/2147483647/strip/true/crop/810x456+0+42/resize/590x332!/format/jpg/quality/90/?url=https%3A%2F%2Fgolf-pass-brightspot.s3.amazonaws.com%2F97%2Fab%2Fbe62a4ff1abb76b4f8e4ad81cd48%2F90009.jpg', website: ''},
        {id: 45, name: 'Ashburton Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 46, name: 'Ben Ohau Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 47, name: 'Fairlie Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 48, name: 'Geraldine District Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 49, name: 'Gleniti Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 50, name: 'Grande Vue Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 51, name: 'Highfield Golf Course', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 52, name: 'Mackenzie Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 53, name: 'Methven Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 54, name: 'Maungati Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 55, name: 'Mt Nessing Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 56, name: 'Pleasant Point Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 57, name: 'Rakaia Golf Club Inc', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 58, name: 'St. Andrews Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 59, name: 'Temuka Golf Club Inc', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 60, name: 'Timaru Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 61, name: 'Tinwald Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 62, name: 'Waimate Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 63, name: 'Auckland Regional Police Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 64, name: 'Akarana Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 65, name: 'Aviation Golf Course', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 66, name: 'Awhitu Golf Club Inc', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 67, name: 'Clarks Beach Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 68, name: 'Rydges Formosa Golf Resort', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 69, name: 'Onewhero Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 70, name: 'Manukau Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 71, name: 'Windross Farm Golf Course', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 72, name: 'Maramarua Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 73, name: 'Maungakiekie Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 74, name: 'Pukekohe Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 75, name: 'Royal Auckland and Grange Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 76, name: 'Waiheke Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 77, name: 'Waiuku Golf & Squash Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 78, name: 'Whitford Park Golf Club Inc', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 79, name: 'The Hamurana Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 80, name: 'Hinehopu Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 81, name: 'Kawerau Golf & Squash Club Inc', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 82, name: 'Kinloch Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 83, name: 'Lake View Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 84, name: 'Motutara Golf Course (Government Gardens)', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 85, name: 'Murupara Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 86, name: 'Ohope International Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 87, name: 'Omanu Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 88, name: 'Omokoroa Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 89, name: 'Opotiki Golf Club Inc', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 90, name: 'Otumoetai Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 91, name: 'Renner Park Golf', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 92, name: 'Rotorua Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 93, name: 'Springfield Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 94, name: 'Taupo Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 95, name: 'Te Puke Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 96, name: 'Te Teko Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 97, name: 'Turangi Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 98, name: 'Waikite Valley Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 99, name: 'Waiotapu Valley Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 100, name: 'Wairakei Golf + Sanctuary', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 101, name: 'Wairakei Resort 9-Hole Public Golf Course', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 102, name: 'Whakatane Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        {id: 103, name: 'Akaroa Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 104, name: 'Amberley Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 105, name: 'Amuri Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 106, name: 'Avondale Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 107, name: 'Burnham Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 108, name: 'Charteris Bay Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 109, name: 'Chatham Islands Golf Course', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 110, name: 'Cheviot Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 111, name: 'Clearwater Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 112, name: 'Coringa Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 113, name: 'Culverden Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 114, name: 'Ellesmere Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 115, name: 'Greendale Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 116, name: 'Hagley Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 117, name: 'Hanmer Springs Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 118, name: 'Harewood Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 119, name: 'Hawarden Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 120, name: 'Kaiapoi Golf Club Inc', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 121, name: 'Kaituna Golf Course', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 122, name: 'Lincoln Golf Club Inc', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 123, name: 'McLeans Island Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 124, name: 'Pegasus Golf & Sports Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 125, name: 'Rangiora Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 126, name: 'Rawhiti Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 127, name: 'Ferrymead Golf', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 128, name: 'Russley Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 129, name: 'Scargill Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 130, name: 'Tai Tapu Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 131, name: 'Templeton Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 132, name: 'Waimairi Beach Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 133, name: 'Waimakariri Gorge Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 134, name: 'Waitikiri Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 135, name: 'Weedons Country Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 136, name: 'Bottle Lake Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 137, name: 'Cape Turnagain Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 138, name: 'Dannevirke Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 139, name: 'Flemington Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 140, name: 'Hastings Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 141, name: 'Hawkes Bay Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 142, name: 'Karamu Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 143, name: 'Mahia Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 144, name: 'Golflands', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 145, name: 'Maraenui Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 146, name: 'Napier Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 147, name: 'Norsewood Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 148, name: 'Ongaonga Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 149, name: 'Pongaroa Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 150, name: 'Porangahau Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 151, name: 'Puketitiri Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 152, name: 'Te Pohue Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 153, name: 'Waipawa Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 154, name: 'Waipukurau Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 155, name: 'Wairoa Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 156, name: 'Apiti Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 157, name: 'Brookfields Park Golf Course', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 158, name: 'Buckley Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 159, name: 'Castlecliff Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 160, name: 'Feilding Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 161, name: 'Foxton Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 162, name: 'Hawkestone Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 163, name: 'Levin Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 164, name: 'Linton Camp Golf Course', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 165, name: 'Marton Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 166, name: 'Pahiatua Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 167, name: 'Palmerston North Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 168, name: 'Paraparaumu Beach Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 169, name: 'Rangatira Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 170, name: 'Rangitikei Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 171, name: 'Taihape Golf Course', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 172, name: 'River City Golf', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 173, name: 'Waimarino Golf Club', country: 'New Zealand', region: 'Manawatu-Wanganui', regionNumber: 1, photo: '', website: ''},
        {id: 174, name: 'Gulf Harbour Country Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 175, name: 'Helensville District Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 176, name: 'Omaha Beach Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 177, name: 'Wainui Golf and Function Centre', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 178, name: 'Pupuke Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 179, name: 'South Head Golf Club Inc', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 180, name: 'Waitemata Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 181, name: 'Warkworth Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 182, name: 'Whangaparaoa Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 183, name: 'Bay of Islands Golf Club Kerikeri', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 184, name: 'Carrington Estate', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 185, name: 'Hikurangi Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 186, name: 'Houhora Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 187, name: 'Kaikohe Golf and Squash Club Inc', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 188, name: 'Kaitaia Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 189, name: 'Kauri Cliffs Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 190, name: 'Mataura Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 191, name: 'Ngunguru Golf Course', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 192, name: 'Northern Wairoa Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 193, name: 'Northland Golf Course', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 194, name: 'Okaihau Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 195, name: 'Paparoa Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 196, name: 'Rawene Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 197, name: 'Sherwood Park Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 198, name: 'Tapora Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 199, name: 'The Pines Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 200, name: 'Waiotira Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 201, name: 'Waitangi Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 202, name: 'Wellsford Golf Club Inc', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 203, name: 'Whangarei Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 204, name: 'Whangaroa Golf Club', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 205, name: 'Alexandra Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 206, name: 'Allan Grange Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 207, name: 'Ardleigh Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 208, name: 'Arrowtown Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 209, name: 'Balclutha Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 210, name: 'Belleknowes Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 211, name: 'Lower Waitaki Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 212, name: 'Clinton Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 213, name: 'Cromwell Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 214, name: 'Dunstan Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 215, name: 'Gladfield Country Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 216, name: 'Glenorchy Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 217, name: 'Heriot Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 218, name: 'Island Park Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 219, name: "Jack's Point Golf Course", country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 220, name: 'Kaitangata Golf Course', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 221, name: 'Kurow Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 222, name: 'Lawrence Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 223, name: 'Maniototo Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 224, name: 'Middlemarch Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 225, name: 'Millbrook Resort', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 226, name: 'Naseby Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 227, name: 'North Otago Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 228, name: 'Omakau Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 229, name: 'Omarama Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 230, name: 'Otakou Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 231, name: 'Otematata Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 232, name: 'Owaka Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 233, name: 'Patearoa Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 234, name: 'Port Chalmers Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 235, name: 'Roxburgh Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 236, name: 'Saint Clair Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 237, name: 'Taieri Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 238, name: 'Tapanui Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 239, name: 'Tarras Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 240, name: 'The Hills Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 241, name: 'Tokarahi Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 242, name: 'Toko Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 243, name: 'Twelve Oaks Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 244, name: 'Waikouaiti Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 245, name: 'Waitoa Park Golf Club', country: 'New Zealand', region: 'Otago', regionNumber: 13, photo: '', website: ''},
        {id: 246, name: 'Gisborne Park Golf Club', country: 'New Zealand', region: 'Gisborne District', regionNumber: 2, photo: '', website: ''},
        {id: 247, name: 'Waikohu Golf Club', country: 'New Zealand', region: 'Gisborne District', regionNumber: 2, photo: '', website: ''},
        {id: 248, name: 'Poverty Bay Golf Club', country: 'New Zealand', region: 'Gisborne District', regionNumber: 2, photo: '', website: ''},
        {id: 249, name: 'Tahunga Golf Club', country: 'New Zealand', region: "Hawke's Bay", regionNumber: 3, photo: '', website: ''},
        {id: 250, name: 'Te Puia Hot Springs Golf Club', country: 'New Zealand', region: 'Gisborne District', regionNumber: 2, photo: '', website: ''},
        {id: 251, name: 'Tolaga Bay Golf Club', country: 'New Zealand', region: 'Gisborne District', regionNumber: 2, photo: '', website: ''},
        {id: 252, name: 'Bluff Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 253, name: 'Dipton Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 254, name: 'Drummond Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 255, name: 'Gore Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 256, name: 'Green Acres Country Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 257, name: 'Hedgehope Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 258, name: 'Kingston Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 259, name: 'Lumsden Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 260, name: 'Mataura Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 261, name: 'Mossburn Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 262, name: 'Nightcaps Golf Course', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 263, name: 'Ohai Golf Course', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 264, name: 'Otautau Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 265, name: 'Queens Park Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 266, name: 'Ringa Ringa Heights Golf Course', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 267, name: 'Riversdale Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 268, name: 'Riverton Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 269, name: 'Southland Golf Course', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 270, name: 'Te Anau Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 271, name: 'Tokanui Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 272, name: 'Tuatapere Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 273, name: 'Waikaia Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 274, name: 'Waikaka Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 275, name: 'Winton Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 276, name: 'Wyndham Golf Club', country: 'New Zealand', region: 'Southland', regionNumber: 14, photo: '', website: ''},
        {id: 277, name: 'Eltham Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 278, name: 'Hawera Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 279, name: 'Inglewood Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 280, name: 'Kaitake Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 281, name: 'Manaia Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 282, name: 'Manukorihi Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 283, name: 'St. Andrews Of New Plymouth', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 284, name: 'Opunake Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 285, name: 'Patea Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 286, name: 'Pungarehu Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 287, name: 'Stratford Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 288, name: 'Strathmore Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 289, name: 'Taranui Golf Course', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 290, name: 'Te Ngutu Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 291, name: 'Urenui Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 292, name: 'Waitara Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 293, name: 'Waverley Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 294, name: 'Westown Golf Club', country: 'New Zealand', region: 'Taranaki', regionNumber: 11, photo: '', website: ''},
        {id: 295, name: 'Awatere Golf Club', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: '', website: ''},
        {id: 296, name: 'Golden Downs Golf Club', country: 'New Zealand', region: 'Tasman District', regionNumber: 9, photo: '', website: ''},
        {id: 297, name: 'Greenacres Golf Club', country: 'New Zealand', region: 'Tasman District', regionNumber: 9, photo: '', website: ''},
        {id: 298, name: 'Ikamatua Golf Club', country: 'New Zealand', region: 'West Coast', regionNumber: 12, photo: '', website: ''},
        {id: 299, name: 'Kaikoura Golf Club', country: 'New Zealand', region: 'Canterbury', regionNumber: 6, photo: '', website: ''},
        {id: 300, name: 'Karamea Golf Club', country: 'New Zealand', region: 'West Coast', regionNumber: 12, photo: '', website: ''},
        {id: 301, name: 'Motueka Golf Club', country: 'New Zealand', region: 'Tasman District', regionNumber: 9, photo: '', website: ''},
        {id: 302, name: 'Murchison Golf Course', country: 'New Zealand', region: 'Tasman District', regionNumber: 9, photo: '', website: ''},
        {id: 303, name: 'Nopera Golf Course', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: '', website: ''},
        {id: 304, name: 'Picton Golf Club', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: '', website: ''},
        {id: 305, name: 'Rarangi Golf Club', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: '', website: ''},
        {id: 306, name: 'Reefton Golf Club', country: 'New Zealand', region: 'West Coast', regionNumber: 12, photo: '', website: ''},
        {id: 307, name: 'RNZAF Base Woodbourne Golf Club', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: '', website: ''},
        {id: 308, name: 'Tasman Golf Club', country: 'New Zealand', region: 'Auckland', regionNumber: 4, photo: '', website: ''},
        {id: 309, name: 'Wairau Valley Golf Club', country: 'New Zealand', region: 'Marlborough District', regionNumber: 7, photo: '', website: ''},
        {id: 310, name: 'Westport Golf Club', country: 'New Zealand', region: 'West Coast', regionNumber: 12, photo: '', website: ''},
        {id: 311, name: 'Whataroa Golf Course', country: 'New Zealand', region: 'West Coast', regionNumber: 12, photo: '', website: ''},
        {id: 312, name: 'Cambridge Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 313, name: 'Coromandel Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 314, name: 'Hauraki Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 315, name: 'Horsham Downs Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 316, name: 'Hukanui Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 317, name: 'Huntly Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 318, name: 'Kawhia Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 319, name: 'Mangakino Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 320, name: 'Matamata Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 321, name: 'Paeroa Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 322, name: 'Morrinsville Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 323, name: 'Riverside Golf Club Narrows Course', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 324, name: 'Ngahinapouri Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 325, name: 'Ngaruawahia Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 326, name: 'Okoroire Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 327, name: 'Pauanui Pines Golf Course', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 328, name: 'Piopio Aria Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 329, name: 'Pirongia Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 330, name: 'Purangi Golf & Country Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 331, name: 'Putaruru Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 332, name: 'Raglan Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 333, name: 'Stewart Alexander Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 334, name: 'Tahuna Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 335, name: 'Tairua Golf and Country Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 336, name: 'Taumarunui Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 337, name: 'Te Aroha Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 338, name: 'Te Awamutu Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 339, name: 'Te Kowhai Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 340, name: 'Thames Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 341, name: 'The Dunes Matarangi Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 342, name: 'Tirau Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 343, name: 'Tokoroa Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 344, name: 'Waikare Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 345, name: 'Waiterimu Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 346, name: 'Waitomo Golf & Country Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 347, name: 'Walton Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 348, name: 'Whangamata Golf Club', country: 'New Zealand', region: 'Waikato', regionNumber: 15, photo: '', website: ''},
        {id: 349, name: "Boulcott's Farm Heritage Golf Club", country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 350, name: 'Carterton Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 351, name: 'Castlepoint Golf Course', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 352, name: 'Eketahuna Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 353, name: 'Judgeford Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 354, name: 'Kapiti Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 355, name: 'Karori Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 356, name: 'Mahunga Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 357, name: 'Manor Park Golf Sanctuary', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 358, name: 'Martinborough Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 359, name: 'Masterton Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 360, name: 'Mornington Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 361, name: 'Ohariu Valley Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 362, name: 'Otaki Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 363, name: 'The Morgans Golf Course', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 364, name: 'Riversdale Beach Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 365, name: 'Shandon Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 366, name: 'Silverstream Public Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 367, name: 'Te Marua Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 368, name: 'Titahi Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 369, name: 'Trentham Camp Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 370, name: 'Waikanae Golf Club', country: 'New Zealand', region: 'Wellington', regionNumber: 16, photo: '', website: ''},
        {id: 371, name: 'Tara Iti', country: 'New Zealand', region: 'Northland', regionNumber: 10, photo: '', website: ''},
        {id: 372, name: 'Mt Maunganui Golf Club', country: 'New Zealand', region: 'Bay of Plenty', regionNumber: 5, photo: '', website: ''},
        
        
        

      ]);
    });
};